language: php

php:
  - 7.4
  - 8.0
  - 8.1

sudo: false

env:
  matrix:
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: PHPCS=1 DEFAULT=0

    - php: 7.4
      env: COVERAGE=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - if [[ $PHPCS == 1 ]]; then composer require --dev cakephp/cakephp-codesniffer:^4.0 ; fi

script:
  - if [[ $COVERAGE == 1 ]]; then export XDEBUG_MODE=coverage && vendor/bin/phpunit --coverage-clover=coverage.xml ; fi
  - if [[ $COVERAGE == 1 ]]; then curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -v -f coverage.xml ; fi

  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit --stderr ; fi

  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=tests/bootstrap.php . ; fi

notifications:
  email: false
